# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170725_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vies',
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
